import CouretOaiBridge01.STAT_TRANS_02_ClaimContract

/-!
# STAT-TRANS-03 — Dependency graph and differential invalidation

This file formalizes a minimal dependency graph for claim-contract invalidation.

Orientation:
  edge a b
means:
  b directly depends on a.

A change at a node propagates only to nodes reachable from that node.
The construction is deliberately generic and does not encode a global
"everything invalidates everything" policy.

No RH claim. No novelty claim.
-/

namespace CouretOaiBridge01
namespace StatusTransport

/-- Reflexive-transitive reachability generated by a direct dependency edge. -/
inductive Reach {α : Type*} (edge : α → α → Prop) : α → α → Prop
  | refl (x : α) : Reach edge x x
  | step {a b c : α} : Reach edge a b → edge b c → Reach edge a c

/-- A node is impacted when some changed seed reaches it. -/
def Impacted {α : Type*}
    (edge : α → α → Prop) (changed : α → Prop) (x : α) : Prop :=
  ∃ s, changed s ∧ Reach edge s x

/-- Every changed seed is impacted. -/
theorem changed_seed_impacted
    {α : Type*} {edge : α → α → Prop} {changed : α → Prop}
    {x : α} (hx : changed x) :
    Impacted edge changed x := by
  exact ⟨x, hx, Reach.refl x⟩

/-- Impact propagates across one direct dependency edge. -/
theorem impacted_of_edge
    {α : Type*} {edge : α → α → Prop} {changed : α → Prop}
    {a b : α}
    (ha : Impacted edge changed a)
    (hab : edge a b) :
    Impacted edge changed b := by
  rcases ha with ⟨s, hs, hreach⟩
  exact ⟨s, hs, Reach.step hreach hab⟩

/--
A node that is unreachable from every changed seed is not impacted.
This is the core "no global invalidation" theorem.
-/
theorem not_impacted_of_unreachable
    {α : Type*} {edge : α → α → Prop} {changed : α → Prop}
    {x : α}
    (h : ∀ s, changed s → ¬ Reach edge s x) :
    ¬ Impacted edge changed x := by
  intro hx
  rcases hx with ⟨s, hs, hsx⟩
  exact h s hs hsx

/-- A direct dependent of a changed seed is impacted. -/
theorem direct_dependent_impacted
    {α : Type*} {edge : α → α → Prop} {changed : α → Prop}
    {a b : α}
    (ha : changed a)
    (hab : edge a b) :
    Impacted edge changed b := by
  exact impacted_of_edge (changed_seed_impacted ha) hab

/--
A dependency-free node distinct from all changed seeds is not impacted.
This makes explicit that isolated claims survive unrelated changes.
-/
theorem isolated_node_not_impacted
    {α : Type*} {edge : α → α → Prop} {changed : α → Prop}
    {x : α}
    (hseed : ¬ changed x)
    (hin : ∀ y, ¬ edge y x) :
    ¬ Impacted edge changed x := by
  apply not_impacted_of_unreachable
  intro s hs hreach
  cases hreach with
  | refl =>
      exact hseed hs
  | step _ hlast =>
      exact hin _ hlast

/--
A changed contract carries both its local delta and its location in the
dependency graph.  Later layers may refine this into per-axis edge labels.
-/
structure ChangeAt (α : Type*) where
  node : α
  delta : Delta

/--
Semantic invalidation seeds only those local changes whose delta says that
semantics must be reconsidered.
-/
def SemanticSeed {α : Type*} (changes : List (ChangeAt α)) (x : α) : Prop :=
  ∃ c ∈ changes, c.node = x ∧ c.delta.invalidatesSemantic = true

/--
Replay invalidation seeds local changes whose delta invalidates replay.
-/
def ReplaySeed {α : Type*} (changes : List (ChangeAt α)) (x : α) : Prop :=
  ∃ c ∈ changes, c.node = x ∧ c.delta.invalidatesReplay = true

/--
Novelty invalidation seeds local changes whose delta invalidates novelty.
-/
def NoveltySeed {α : Type*} (changes : List (ChangeAt α)) (x : α) : Prop :=
  ∃ c ∈ changes, c.node = x ∧ c.delta.invalidatesNovelty = true

/-- Graph-level semantic invalidation. -/
def SemanticImpacted {α : Type*}
    (edge : α → α → Prop) (changes : List (ChangeAt α)) (x : α) : Prop :=
  Impacted edge (SemanticSeed changes) x

/-- Graph-level replay invalidation. -/
def ReplayImpacted {α : Type*}
    (edge : α → α → Prop) (changes : List (ChangeAt α)) (x : α) : Prop :=
  Impacted edge (ReplaySeed changes) x

/-- Graph-level novelty invalidation. -/
def NoveltyImpacted {α : Type*}
    (edge : α → α → Prop) (changes : List (ChangeAt α)) (x : α) : Prop :=
  Impacted edge (NoveltySeed changes) x

end StatusTransport
end CouretOaiBridge01
